In [35]:
from scipy.io import wavfile
###Use librosa

In [36]:
samplerate, data = wavfile.read(r'C:\Users\Mridul Gupta\Downloads\Compressed\speech_commands_v0.01\six\0ab3b47d_nohash_0.wav')
print(data.shape)
print(type(data))

(12971,)
<class 'numpy.ndarray'>


In [37]:
from pathlib import Path
import numpy as np


In [38]:
p=Path(r'C:\Users\Mridul Gupta\Downloads\Compressed\speech_commands_v0.01')

In [39]:
dirs=p.glob("*")
labels=[]
audio_data=[]
Y=[]
dict={}
i=0
for folder_dir in dirs:
    print(folder_dir)
    
    label=str(folder_dir).split("\\")[-1]
    labels.append(label)
    dict.update({label:i})
    
    for aud in folder_dir.glob("*.wav"):
        sample_rate,data=wavfile.read(aud)
        #print(data)
        #print(type(data))
        #print(data.shape)
        #print(type(data))
        data=data.reshape((data.shape[0],))
        audio_data.append(data)
        Y.append(i)
        
    
    
    i+=1
    #print(label)

C:\Users\Mridul Gupta\Downloads\Compressed\speech_commands_v0.01\six


In [40]:
print(dict)

{'six': 0}


In [41]:
audio_data 

[array([ -2,   2,   7, ..., -34, -29, -19], dtype=int16),
 array([  67,  175,  161, ...,  -74, -230,  277], dtype=int16),
 array([-5, -7,  3, ...,  5,  7,  8], dtype=int16),
 array([-2, -2, -2, ...,  3,  3,  3], dtype=int16)]

In [42]:
audio_data=np.array(audio_data)

In [43]:
audio_data.shape


(4,)

In [46]:
check=np.array(audio_data)
print(check.shape)

(4,)


In [7]:
print(type(audio_data))

audio_data=np.array(audio_data)
print(type(audio_data))

<class 'list'>
<class 'numpy.ndarray'>


In [8]:
X=np.array(audio_data)
print(type(X))

<class 'numpy.ndarray'>


In [9]:
print(X.shape)
print(X[0].shape)

(1750,)
(16000,)


In [10]:
X_=np.array(X)
print(type(X))
print(type(X_))

print(X_.shape)



<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
(1750,)


In [ ]:
#split=1000

In [ ]:
#X_train=X_[:split]


In [ ]:
print(X_train.shape)
print(X_train[0].shape)

In [ ]:
Y_=np.array(Y)

In [ ]:
print(X[150].shape)

In [ ]:
type(X[0])

In [ ]:
#xxx=X.reshape((X.shape[0],-1))


In [ ]:
#print(xxx.shape)
#print(type(xxx[0]))

In [ ]:
split=3000

In [ ]:
print(X_.shape)
print(Y_.shape)

print(X_[0].shape)
print(type(X_[0]))


In [ ]:
first=X_[0]

In [ ]:
print(X_)

In [ ]:
X_=np.reshape(X_,(4115,16000))
print(X_.shape)

In [ ]:
X_train=X_[:split]
Y_train=Y_[:split]

X_test=X_[split:]
y_test=Y_[split:]