In [172]:
import numpy as np
import pandas as pd

from nltk.tokenize import RegexpTokenizer
from nltk.stem.porter import PorterStemmer
from nltk.corpus import stopwords


tokenizer = RegexpTokenizer(r'\w+')
en_stopwords= set(stopwords.words('english'))
ps=PorterStemmer()

In [190]:
tx=open(r'C:\Users\Mridul Gupta\Jupyter Notebook\Naive Bayes\my_test_data.txt',encoding="utf8")
ty=open(r'C:\Users\Mridul Gupta\Jupyter Notebook\Naive Bayes\my_test_y.txt',encoding="utf8")

In [191]:
my_data_x=tx.read()
my_data_y=ty.read()


In [192]:
#print(my_data_x)

In [193]:
type(my_data_x)


str

In [194]:
type(my_data_y)

str

In [195]:
#print(my_data)

In [196]:
my_data_x=my_data_x.splitlines()
my_data_y=my_data_y.splitlines()


In [197]:
type(my_data_x)

list

In [198]:
type(my_data_y)

list

In [199]:
def getCleanReview(review):
    
    review=review.lower()
    review=review.replace("</br></br>", " ")
    
    #Tokenize
    
    tokens = tokenizer.tokenize(review)
    new_tokens= [token for token in tokens if token not in en_stopwords]
    
    stemmed_tokens= [ps.stem(token) for token in new_tokens]
    
    cleaned_review=' '.join(stemmed_tokens)
    
    return cleaned_review

In [200]:
x_clean= [getCleanReview(i) for i in my_data_x]

In [201]:
#print(x_clean)

In [202]:
type(my_data_y)

list

In [203]:
testing_case=['it was a bad movie. Do not watch. Poor casting, sab poor.first grade. dialogue not good ']
xt_clean=[getCleanReview(i) for i in testing_case]

In [204]:
from sklearn.feature_extraction.text import CountVectorizer

In [205]:
cv = CountVectorizer(ngram_range=(1,2))

x_vec = cv.fit_transform(x_clean).toarray()
print(x_vec)
print(x_vec.shape)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [2 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(50, 8659)


In [206]:
## Vectorization on the test set
xt_vec = cv.transform(xt_clean).toarray()
print(xt_vec)
cv.get_feature_names()
print(xt_vec.shape)

[[0 0 0 ... 0 0 0]]
(1, 8659)


In [207]:
from sklearn.naive_bayes import MultinomialNB,BernoulliNB, GaussianNB


In [208]:
mnb = MultinomialNB()
print(mnb)
MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

# Training 
mnb.fit(x_vec,my_data_y)



#Predictions
mnb.predict(xt_vec)

mnb.predict_proba(xt_vec)

#mnb.score(x_vec,y)


MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)


array([[9.79751831e-01, 1.22945848e-03, 1.89746803e-02, 4.40300208e-05]])

In [209]:
mnb.predict(xt_vec)


array(['10'], dtype='<U2')