# Mushroom Dataset


In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv(r"C:\Users\Mridul Gupta\Jupyter Notebook\Datasets\mushrooms.csv")
df.head(n=10)

type cap_shape cap_surface cap_color bruises odor gill_attachment  \
0    p         x           s         n       t    p               f   
1    e         x           s         y       t    a               f   
2    e         b           s         w       t    l               f   
3    p         x           y         w       t    p               f   
4    e         x           s         g       f    n               f   
5    e         x           y         y       t    a               f   
6    e         b           s         w       t    a               f   
7    e         b           y         w       t    l               f   
8    p         x           y         w       t    p               f   
9    e         b           s         y       t    a               f   

  gill_spacing gill_size gill_color   ...   stalk_surface_below_ring  \
0            c         n          k   ...                          s   
1            c         b          k   ...                          s   
2            c         b          n   ...                          s   
3            c         n          n   ...                          s   
4            w         b          k   ...                          s   
5            c         b          n   ...                          s   
6            c         b          g   ...                          s   
7            c         b          n   ...                          s   
8            c         n          p   ...                          s   
9            c         b          g   ...                          s   

  stalk_color_above_ring stalk_color_below_ring veil_type veil_color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   
5                      w                      w         p          w   
6                      w                      w         p          w   
7                      w                      w         p          w   
8                      w                      w         p          w   
9                      w                      w         p          w   

  ring_number ring_type spore_print_color population habitat  
0           o         p                 k          s       u  
1           o         p                 n          n       g  
2           o         p                 n          n       m  
3           o         p                 k          s       u  
4           o         e                 n          a       g  
5           o         p                 k          n       g  
6           o         p                 k          n       m  
7           o         p                 n          s       m  
8           o         p                 k          v       g  
9           o         p                 k          s       m  

[10 rows x 23 columns]

In [3]:
#change this data to numerical data
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [4]:
le=LabelEncoder()
ds=df.apply(le.fit_transform) #applies transformation on each column

#print(ds)

#convert to np array
data=ds.values
print(data.shape)
print(data[:5,:])

(8124, 23)
[[1 5 2 4 1 6 1 0 1 4 0 3 2 2 7 7 0 2 1 4 2 3 5]
 [0 5 2 9 1 0 1 0 0 4 0 2 2 2 7 7 0 2 1 4 3 2 1]
 [0 0 2 8 1 3 1 0 0 5 0 2 2 2 7 7 0 2 1 4 3 2 3]
 [1 5 3 8 1 6 1 0 1 5 0 3 2 2 7 7 0 2 1 4 2 3 5]
 [0 5 2 3 0 5 1 1 0 4 1 3 2 2 7 7 0 2 1 0 3 0 1]]


In [5]:
data_y=data[:,0]
data_x=data[:,1:]

In [6]:
##Break this data into train and test
x_train,x_test,y_train,y_test=train_test_split(data_x,data_y,test_size=0.2)

In [7]:
print(x_train.shape)
print(x_test.shape)

(6499, 22)
(1625, 22)


In [8]:
print(y_test.shape)
print(y_train.shape)

(1625,)
(6499,)


# Build our Classifier

In [60]:
a= np.array([0,0,0,0,1,1])
print(a==1)

[False False False False  True  True]


In [61]:
def prior_prob(y_train,label):
    total_example= y_train.shape[0]
    class_example= np.sum(y_train==label)
    
    return (class_example)/float(total_example)
    

In [62]:
#y=np.array([0,1,1,1,0])
#print(prior_prob(y,1))

In [137]:
def cond_prob(x_train,y_train,feature_col,feature_val,label):
    
    x_filtered = x_train[y_train==label]
    numerator = np.sum(x_filtered[:,feature_col]==feature_val)
    denominator = np.sum(y_train==label)
    
    return numerator/float(denominator)

In [151]:
def predict(x_train,y_train,xtest):
    
    #xtest is a single testing point with n features
    
    classes= np.unique(y_train)
    n_features= x_train.shape[1]
    
    post_prob=[]
    

    #compute posterior for all casses
    
    for label in classes:
        
        #likelihood*prior
        likelihood=1.0
        
        for f in range(n_features):
            cond=cond_prob(x_train,y_train,f,xtest[f],label)
            
            likelihood*=cond
        prior=prior_prob(y_train,label)
        
        post=prior*likelihood
        
        #lets append this to an array nad then select kar lenge usme se
        
        post_prob.append(post)
        
    pred=np.argmax(post_prob)
    return pred
    

In [160]:
def score(x_test,y_test,x_train,y_train):
    score=1.0
    for i in range(y_test.shape[0]):
        if predict(x_train,y_train,x_test[i]) == y_test[i]:
            score+=1
    return float(score/y_test.shape[0])
    

In [163]:
ans=score(x_test,y_test,x_train,y_train)

print(ans)

0.9993846153846154


Pratteks code

In [133]:

def prior_prob(y_train,label):
    
    total_examples = y_train.shape[0]
    class_examples = np.sum(y_train==label)
    
    return (class_examples)/float(total_examples)

In [134]:
def cond_prob(x_train,y_train,feature_col,feature_val,label):
    
    x_filtered = x_train[y_train==label]
    numerator = np.sum(x_filtered[:,feature_col]==feature_val)
    denominator = np.sum(y_train==label)
    
    return numerator/float(denominator)

In [135]:
def predict(x_train,y_train,xtest):
    """Xtest is a single testing point, n features"""
    
    classes = np.unique(y_train)
    n_features = x_train.shape[1]
    post_probs = [] # List of prob for all classes and given a single testing point
    #Compute Posterior for each class
    for label in classes:
        
        #Post_c = likelihood*prior
        likelihood = 1.0
        for f in range(n_features):
            cond = cond_prob(x_train,y_train,f,xtest[f],label)
            likelihood *= cond 
            
        prior = prior_prob(y_train,label)
        post = likelihood*prior
        post_probs.append(post)
        
    pred = np.argmax(post_probs)
    return pred

In [136]:
output = predict(x_train,y_train,x_test[1])
print(output)
print(y_test[1])

1
1


In [157]:
for i in range(y_test.shape[0]):
    #print(i)

SyntaxError: unexpected EOF while parsing (<ipython-input-157-c268632f70f9>, line 2)

In [9]:
from sklearn.datasets import load_digits
from sklearn.model_selection import cross_val_score

In [14]:
from sklearn.naive_bayes import MultinomialNB,GaussianNB

In [15]:
mnb=MultinomialNB()
gnb=GaussianNB()

In [16]:
mnb.fit(x_test,y_test)
gnb.fit(x_test,y_test)

GaussianNB(priors=None)

In [18]:
print(mnb.score(x_test,y_test))
print(gnb.score(x_test,y_test))

0.7944615384615384
0.9286153846153846
