In [1]:
import numpy as np
import pandas as pd

from nltk.tokenize import RegexpTokenizer
from nltk.stem.porter import PorterStemmer
from nltk.corpus import stopwords


tokenizer = RegexpTokenizer(r'\w+')
en_stopwords= set(stopwords.words('english'))
ps=PorterStemmer()

In [2]:
tx=open(r'imdb_testX.txt',encoding="utf8")
ty=open(r'imdb_testY.txt',encoding="utf8")

In [3]:
my_data_x=tx.read()
my_data_y=ty.read()



In [4]:
#print(my_data_x)

In [5]:
type(my_data_x)


str

In [6]:
type(my_data_y)

str

In [7]:
#print(my_data)

In [8]:
my_data_x=my_data_x.splitlines()
my_data_y=my_data_y.splitlines()

my_data_x = my_data_x[:500]
my_data_y = my_data_y[:500]


In [9]:
type(my_data_x)


list

In [10]:
type(my_data_y)

list

In [11]:
temp_sent=["It was a fine movie. i liked it"]

In [12]:
print(type(my_data_x[0]))

<class 'str'>


In [13]:
def getCleanReview(review):
    
    review=review.lower()
    review=review.replace("</br></br>", "")
    
    #Tokenize
    
    tokens = tokenizer.tokenize(review)
    new_tokens= [token for token in tokens if token not in en_stopwords]
    
    stemmed_tokens= [ps.stem(token) for token in new_tokens]
    
    cleaned_review=' '.join(stemmed_tokens)
    
    
    return cleaned_review

In [14]:
x_clean= [getCleanReview(i) for i in my_data_x]

In [15]:
print(type(x_clean))

<class 'list'>


In [17]:
print(type(x_clean))

<class 'list'>


In [111]:
print(type(x_clean))
print(x_clean[0])

<class 'list'>
realli sure make movi weird artsi kind movi watch compel plot charact like kind movi stop watch horrif fascin thing happen screen although first time wife watch make way disturb run bit long nonetheless worthwhil view interest dark movi


In [112]:
aaa=x_clean[:20]

In [19]:
#for i in my_data_x[0]:
    #print(i)

In [20]:
#print(x_clean)

In [115]:
type(my_data_y)

list

In [116]:
my_data_x[1]

"If you enjoyed films like Pulp Fiction, Reservoir Dogs, and Lock, Stock, and Two Smoking Barrels, you are going to LOVE Two Hands. It has the same type of black humor beat to it and will keep you entertained through the whole film. Like Pulp Fiction, it has the wacky scenarios that the characters get into and how they deal with them. Along with Gallipoli and Picnic at Hanging Rock, this has to be one of the best Australian films I've seen. It also stars a young Heath Ledger before he got real big in the states.<br /><br />This is a terribly underrated movie that I believe is just as good as Pulp Fiction and those greats. You have to see it!"

In [127]:
testing_case=['Worst movie. Do not watch. Time waste']
xt_clean=[getCleanReview(i) for i in testing_case]

In [128]:
for i in testing_case:
    print(i)
print(type(testing_case))

Worst movie. Do not watch. Time waste
<class 'list'>


In [129]:
print(xt_clean)

['worst movi watch time wast']


In [130]:
len(x_clean)

500

In [25]:
print(type(x_clean[0]))
type(x_clean)

<class 'str'>


list

In [23]:
from sklearn.feature_extraction.text import CountVectorizer

In [24]:
cv = CountVectorizer(ngram_range=(1,2))

x_vec = cv.fit_transform(x_clean).toarray()
print(x_vec)
print(x_vec.shape)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(500, 53488)


In [133]:
## Vectorization on the test set
xt_vec = cv.transform(xt_clean).toarray()
print(xt_vec)
cv.get_feature_names()
print(xt_vec.shape)

[[0 0 0 ... 0 0 0]]
(1, 53488)


In [134]:
from sklearn.naive_bayes import MultinomialNB,BernoulliNB, GaussianNB


In [135]:
mnb = MultinomialNB()
print(mnb)
MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

# Training 
mnb.fit(x_vec,my_data_y)



#Predictions
mnb.predict(xt_vec)

mnb.predict_proba(xt_vec)

#mnb.score(x_vec,y)


MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)


array([[0.95362382, 0.02427111, 0.00454671, 0.01755836]])

In [136]:
mnb.predict(xt_vec)


array(['10'], dtype='<U2')