Make a dataset of poems and try categorising them in 4 genres using two different classifiers. Training data shall not exceed 1000 poems and 50,000 words in total. Dataset shall be found online and any pre-processing shall be done by intern himself/herself.

In [211]:
import numpy as np
import pandas as pd


from sklearn.feature_extraction.text import CountVectorizer

from nltk.tokenize import RegexpTokenizer
from nltk.stem.porter import PorterStemmer
from nltk.corpus import stopwords


tokenizer = RegexpTokenizer(r'\w+')
en_stopwords= set(stopwords.words('english'))
ps=PorterStemmer()

In [212]:
data=pd.read_csv(r'C:\Users\Mridul Gupta\Jupyter Notebook\Test_Assignments_Extras\all.csv')

data.head(4)

author  \
0                      WILLIAM SHAKESPEARE   
1  DUCHESS OF NEWCASTLE MARGARET CAVENDISH   
2                           THOMAS BASTARD   
3                           EDMUND SPENSER   

                                             content  \
0  Let the bird of loudest lay\r\nOn the sole Ara...   
1  Sir Charles into my chamber coming in,\r\nWhen...   
2  Our vice runs beyond all that old men saw,\r\n...   
3  Lo I the man, whose Muse whilome did maske,\r\...   

                                 poem name          age                  type  
0               The Phoenix and the Turtle  Renaissance  Mythology & Folklore  
1                 An Epilogue to the Above  Renaissance  Mythology & Folklore  
2                       Book 7, Epigram 42  Renaissance  Mythology & Folklore  
3  from The Faerie Queene: Book I, Canto I  Renaissance  Mythology & Folklore

In [213]:
X_train=data.iloc[:400,1].values
Y_train=data.iloc[:400,4:].values

X_test=data.iloc[1:2,1].values
Y_test=data.iloc[1:2,4:].values

In [214]:
#print(Y[2])
#print(X[0])

In [215]:
print(type(X))

<class 'numpy.ndarray'>


In [216]:
def getCleanPoem(P):
    
    P=P.lower()
    P=P.replace("\r\n", "")
    
    #Tokenize
    
    tokens = tokenizer.tokenize(P)
    new_tokens= [token for token in tokens if token not in en_stopwords]
    
    stemmed_tokens= [ps.stem(token) for token in new_tokens]
    
    cleaned_Poem=' '.join(stemmed_tokens)
    #cleaned_Poem = cleaned_Poem.splitlines()
    
    return (cleaned_Poem)    

In [217]:
#test=getCleanPoem(X[0])

In [218]:
#print(test)

In [219]:
#(type(test))

In [220]:
x_train_clean= [getCleanPoem(i) for i in X_train]

x_test_clean= [getCleanPoem(i) for i in X_test]

In [221]:
#print(type(x_clean))
#print(x_clean[2])
#print(type(x_clean[0]))

In [222]:
#print(len(x_clean))

In [223]:
#type(x_clean)

In [224]:

cv = CountVectorizer(ngram_range=(1,2))

x_vec = cv.fit_transform(x_train_clean).toarray()
print(x_vec)
print(x_vec.shape)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(400, 42224)


In [225]:
## Vectorization on the test set
xt_vec = cv.transform(x_test_clean).toarray()
print(xt_vec)
cv.get_feature_names()
print(xt_vec.shape)

[[0 0 0 ... 0 0 0]]
(1, 42224)


In [226]:
from sklearn.naive_bayes import MultinomialNB,BernoulliNB, GaussianNB


mnb = MultinomialNB()
print(mnb)
MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

# Training 
mnb.fit(x_vec,Y_train)



MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)


c:\users\mridul gupta\appdata\local\programs\python\python36-32\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [227]:

#testing
mnb.predict_proba(xt_vec)



#mnb.predict(xt_vec)


array([[1.06237617e-24, 1.00000000e+00, 7.39161624e-31]])

In [228]:
mnb.predict(xt_vec)


array(['Mythology & Folklore'], dtype='<U20')

In [229]:
mnb.score(xt_vec,Y_test)

1.0

In [230]:
print(Y_test)

[['Mythology & Folklore']]
